name: Generate Blogger Sitemap

on:
  workflow_dispatch:  # manual trigger

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      # 4. Generate Blogger Sitemap
      - name: Generate Blogger Sitemap
        run: python generate_blogger_sitemap.py

      # 5. Commit & push sitemap
      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap_blogger.xml
          git commit -m "Auto-update Blogger sitemap" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
