name: Auto-Generate Blogger Sitemap

on:
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Blogger Sitemap Generator
        run: python generate_blogger_sitemap.py

      - name: Commit & Push Blogger Sitemap
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap_blogger.xml
          git commit -m "Auto-update Blogger sitemap" || echo "No changes to commit"
          git fetch origin main
          git reset --hard origin/main
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main --force
