name: Auto-Generate Blogger Sitemap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-blogger-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Blogger sitemap generator
        run: python generate_blogger_sitemap.py

      - name: Commit & Push Blogger Sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap_blogger.xml
          git commit -m "Auto-update Blogger sitemap" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
