name: IndexNow + Google Indexing (GitHub Pages + Blogger)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  secrets: read

jobs:
  index_and_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build URL list from changed GitHub Pages HTML files
        env:
          DOMAIN: aymansalem.github.io
        run: |
          echo "Building URL list from changed HTML files..."
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            FILES=$(git ls-files)
          else
            FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          URLS=()
          while IFS= read -r f; do
            case "$f" in
              *.html|*.htm)
                URLS+=("https://${DOMAIN}/${f}")
                ;;
            esac
          done < <(printf "%s\n" "$FILES")
          printf "%s\n" "${URLS[@]}" > urls.txt
          echo "Initial urls.txt contents:"
          cat urls.txt || true

      - name: Append Blogger URLs from sitemap
        run: |
          BLOGGER_SITEMAP="https://4-hoteliers.blogspot.com/sitemap.xml"
          echo "Fetching Blogger sitemap..."
          curl -s "$BLOGGER_SITEMAP" | grep -oP '(?<=<loc>).*?(?=</loc>)' >> urls.txt || true
          sed -i '/^\s*$/d' urls.txt || true
          sort -u urls.txt -o urls.txt || true
          echo "Final urls.txt contents:"
          cat urls.txt || true

      - name: Submit URLs to Bing IndexNow (only hosts with public key file)
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run
