name: Test Google Indexing API

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to test indexing"
        required: true
        default: "https://aymansalem.github.io/"

permissions:
  contents: read
  secrets: read

jobs:
  test-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Save Google JSON secret
        run: echo "${{ secrets.GOOGLE_JSON }}" > /tmp/google_key.json

      - name: Install Google API Client
        run: python3 -m pip install --upgrade --quiet google-api-python-client google-auth

      - name: Run Test Indexing Request
        run: |
          cat > test_indexing.py << 'EOF'
          import sys
          from google.oauth2 import service_account
          from googleapiclient.discovery import build

          creds_file = "/tmp/google_key.json"
          SCOPES = ["https://www.googleapis.com/auth/indexing"]

          url_to_test = "${{ github.event.inputs.url }}"

          try:
              creds = service_account.Credentials.from_service_account_file(creds_file, scopes=SCOPES)
              service = build("indexing", "v3", credentials=creds, cache_discovery=False)
          except Exception as e:
              print("Failed to initialize Google API client:", e)
              sys.exit(1)

          try:
              response = service.urlNotifications().publish(body={"url": url_to_test, "type": "URL_UPDATED"}).execute()
              print(f"✅ Google indexing updated for: {url_to_test}")
              print(response)
          except Exception as e:
              print(f"❌ Google API error for {url_to_test}: {e}")
          EOF

          python3 test_indexing.py
